import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import { Spline_Sans } from "next/font/google";
import { IBM_Plex_Sans } from "next/font/google";
import { Montserrat } from "next/font/google";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-inter"
});

const splineSansFont = Spline_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-spline-sans"
});

const IBMPlexSensFont = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-IBM-plex-sans"
});

const montSerratFont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} ${splineSansFont.variable} ${IBMPlexSensFont.variable} ${montSerratFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
